#include "postgres.h"
#include "autoindex.h"
#include "utils/builtins.h"
#include "utils/lsyscache.h"
#include "utils/rel.h"
#include "catalog/pg_type.h"
#include "commands/defrem.h"
#include "nodes/makefuncs.h"
#include "storage/ipc.h"
#include "storage/shmem.h"
#include "storage/lwlock.h"
#include "nodes/nodeFuncs.h" /* For makeIndexElem */
#include "nodes/parsenodes.h"

static HTAB *AutoIndexHash = NULL;

Size AutoIndexShmemSize(void) {
    return hash_estimate_size(1024, sizeof(AutoIndexEntry));
}

void AutoIndexShmemInit(void) {
    HASHCTL info;
    info.keysize = sizeof(AutoIndexKey);
    info.entrysize = sizeof(AutoIndexEntry);
    
    /* Corrected: ShmemInitHash takes 4 arguments in this version */
    AutoIndexHash = ShmemInitHash("AutoIndex Hash",
                                  1024,
                                  &info,
                                  HASH_ELEM | HASH_BLOBS);
}

void TrackEqualityPredicate(Oid relid, AttrNumber attnum) {
    if (relid < (Oid) 16384) {/* Skip system catalogs */
        /* Print a message indicating that the system catalog is being skipped */
        ereport(LOG, (errmsg("AutoIndex: Skipping system table %d", relid)));
        return;
    }

    AutoIndexKey key;
    AutoIndexEntry *entry;
    bool found;
    uint32 current_count;

    if (!AutoIndexHash)
        return;

    key.relid = relid;
    key.attnum = attnum;

    LWLockAcquire(AddinShmemInitLock, LW_EXCLUSIVE);

    entry = (AutoIndexEntry *) hash_search(AutoIndexHash, &key, HASH_ENTER, &found);

    if (!found) {
        entry->scan_count = 1;
    } else {
        entry->scan_count++;
    }

    current_count = entry->scan_count;
    LWLockRelease(AddinShmemInitLock);

    if (current_count == AUTOINDEX_THRESHOLD) {
        LWLockAcquire(AddinShmemInitLock, LW_EXCLUSIVE);
        entry->scan_count = 0; 
        LWLockRelease(AddinShmemInitLock);

        ExecuteAutoIndex(relid, attnum);
    }
}

void ExecuteAutoIndex(Oid relid, AttrNumber attnum)
{
    char       *relname_raw;
    char       *attname_raw;
    char       *relname;
    char       *attname;
    IndexStmt  *stmt;
    IndexElem  *iparam;

    /* 1. Get names and immediately copy to fresh memory */
    relname_raw = get_rel_name(relid);
    attname_raw = get_attname(relid, attnum, false);

    if (!relname_raw || !attname_raw)
        return;

    relname = pstrdup(relname_raw);
    attname = pstrdup(attname_raw);

    /* * CRITICAL: These functions (get_rel_name) might leave pins in the catcache. 
     * We don't need them anymore, and we want a clean slate for DefineIndex.
     */

    ereport(LOG,
            (errmsg("AutoIndex: Threshold reached2. Creating index on %s(%s)", 
                    relname, attname)));

    /* 2. Construct the Node structures */
    stmt = makeNode(IndexStmt);
    stmt->idxname = NULL;
    stmt->relation = makeRangeVar(NULL, relname, -1);
    stmt->accessMethod = "btree";
    stmt->tableSpace = NULL;

    iparam = makeNode(IndexElem);
    iparam->name = attname;
    iparam->expr = NULL;
    iparam->indexcolname = NULL;
    iparam->collation = NIL;
    iparam->opclass = NIL;
    iparam->opclassopts = NIL;
    iparam->ordering = SORTBY_DEFAULT;
    iparam->nulls_ordering = SORTBY_NULLS_DEFAULT;
    iparam->location = -1;

    stmt->indexParams = list_make1(iparam);
    stmt->options = NIL;
    stmt->whereClause = NULL;
    stmt->excludeOpNames = NIL;
    stmt->idxcomment = "Auto-generated by SeqScan tracker";
    stmt->indexOid = InvalidOid;
    stmt->unique = false;
    stmt->primary = false;
    stmt->isconstraint = false;
    stmt->deferrable = false;
    stmt->initdeferred = false;
    stmt->transformed = false;
    
    /* * CHANGE: Set concurrent to false. 
     * Inside a running query, 'true' is almost guaranteed to fail 
     * with "cannot run inside a transaction".
     */
    stmt->concurrent = false; 
    stmt->if_not_exists = true;

    PG_TRY();
    {
        /* * DefineIndex is very heavy. Calling it here is "illegal" in standard 
         * Postgres development, but we can force it by ensuring it's not concurrent.
         */
        DefineIndex(NULL, relid, stmt, InvalidOid, InvalidOid, InvalidOid, 
                    0, false, false, false, false, true);
    }
    PG_CATCH();
    {
        FlushErrorState();
        ereport(WARNING,
                (errmsg("AutoIndex: Execution failed. Table may be locked by current scan.")));
    }
    PG_END_TRY();
}